/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author NVT
 */
public class AddFlight extends javax.swing.JFrame {

    /**
     * Creates new form AddMenu
     */
    public AddFlight() {
        initComponents();
         this.setBounds(200, 100, 700, 600);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Add Flight");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 510, 100);

        jLabel2.setText("company");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 160, 40);

        jLabel3.setText("From");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 150, 50);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 110, 210, 50);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 190, 210, 50);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 490, 110, 30);

        jLabel4.setText("To");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 290, 70, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 270, 220, 40);

        jLabel5.setText("Date & Time");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 370, 120, 40);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(220, 360, 200, 50);

        jLabel6.setText("total seats");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 450, 120, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 430, 200, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
          Database d=new Database();
        String company=jTextField1.getText();
        String from=jTextField2.getText();
        String to=jTextField3.getText();
        String date=jTextField4.getText();
        String total=jTextField5.getText();
        
       
        
        try{
            
            PreparedStatement ps=d.con.prepareStatement("INSERT INTO `airticket`.`flight` (\n" +
"`company` ,\n" +
"`from` ,\n" +
"`to` ,\n" +
"`date` ,\n" +
"`seats`\n" +
")values(?,?,?,?,?)");
           ps.setString(1, company);
           ps.setString(2, from);
           ps.setString(3, to);
           ps.setString(4, date);
           ps.setString(5, total);
          
          int val = ps.executeUpdate();
          if(val>=1){
              JOptionPane.showMessageDialog(null, "successfully added");
              
            
          }
          else{
                            JOptionPane.showMessageDialog(null, "not successfully added");

          }
            
        }catch(Exception e){
            System.out.println("cannot register"+e);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
