/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author NVT
 */
public class GenerateBill extends javax.swing.JFrame {

    /**
     * Creates new form GenerateBill
     */
    public GenerateBill() {
        initComponents();
        
         this.setBounds(200, 100, 700, 600);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setText("Start time");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 70, 110, 30);

        jLabel2.setText("end time");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 130, 90, 20);

        jLabel3.setText("Vehicle number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 190, 100, 30);

        jLabel4.setText("Total amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 280, 150, 60);

        jLabel5.setText("Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 400, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Generate Bill");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 10, 220, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 70, 210, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 140, 210, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 200, 210, 40);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 280, 210, 40);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(210, 380, 230, 40);

        jButton1.setText("Generate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 440, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Database d=new Database();
      String stime=jTextField1.getText();
      String etime=jTextField2.getText();
      String vno = jTextField3.getText();
      String total=jTextField4.getText();
      String date=jTextField5.getText();
      
      
      
      
      
      try{
        PreparedStatement ps=d.con.prepareStatement("insert into bill(stime,etime,vno,total,date)values(?,?,?,?,?)");
        ps.setString(1, stime);
        ps.setString(2, etime);
        ps.setString(3, vno);
        ps.setString(4, total);
        ps.setString(5, date);
        
        
        int val = ps.executeUpdate();
        if(val>=1){
            JOptionPane.showMessageDialog(null, "successfully generated");
        }
        else{
            JOptionPane.showMessageDialog(null, " not successfully generated");
        }
      }catch(Exception e){
          System.out.println("cannot insert"+e);
      }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
