/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package air;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author NVT
 */
public class UserRegister extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public UserRegister() {
        initComponents();
        this.setBounds(200, 100, 700, 600);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("User Register");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(183, 28, 350, 77);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 150, 150, 30);

        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 230, 160, 40);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 320, 150, 40);

        jLabel5.setText("Email Id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 410, 90, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 140, 170, 50);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 220, 170, 50);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(220, 310, 180, 50);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 390, 180, 50);

        jButton1.setText("Register Here");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 520, 130, 30);

        jButton2.setText("Already have account Login Here");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 110, 260, 30);

        jLabel6.setText("Phone number");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 460, 90, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(220, 460, 180, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Database d=new Database();
      String name=jTextField1.getText();
      String username=jTextField2.getText();
      String password = jPasswordField1.getText();
      String email=jTextField3.getText();
      String phone=jTextField4.getText();
      
      
      
       boolean flag=true;
       if(name.length()==0)
       {
         JOptionPane.showMessageDialog(this,"please enter username");
         flag=false;
       }
       if(email.length()==0&& flag)
       {
         JOptionPane.showMessageDialog(this,"please enter mail id");
         flag=false;
       }
       if(password.length()==0&& flag)
       {
         JOptionPane.showMessageDialog(this,"please enter password");
         flag=false;
       }
      
       
       if(email.matches("[a-z,0-9]+@[a-z]+.[a-z]+") && flag)
       {
         flag=true;
       }
       else
       {
         JOptionPane.showMessageDialog(this,"not a valid mail id");
         flag=false;
       }
       if(phone.matches("[0-9]+")&&flag)
       {
           flag=true;
       }
       else
       {
           JOptionPane.showMessageDialog(this,"not a valid mobile number");
       }
      
      
      if(flag){
      
      try{
        PreparedStatement ps=d.con.prepareStatement("insert into user(name,username,password,email,phone)values(?,?,?,?,?)");
        ps.setString(1, name);
        ps.setString(2, username);
        ps.setString(3, password);
        ps.setString(4, email);
        ps.setString(5, phone);
        
        
        int val = ps.executeUpdate();
        if(val>=1){
            JOptionPane.showMessageDialog(null, "successfully registered");
        }
        else{
            JOptionPane.showMessageDialog(null, " not successfully registered");
        }
      }catch(Exception e){
          System.out.println("cannot insert"+e);
      }
      }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UserLogin1 uu=new UserLogin1();
        uu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
